name: Java CI with Maven

on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "integration" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate Javadoc
      run: mvn javadoc:javadoc
    - name: Publish Javadoc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/docs/javadoc
